name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - renovate/*

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: lts/-1
          cache: pnpm

      - name: Install dependencies 📦
        run: pnpm install --frozen-lockfile

      - name: Lint project 👀
        run: pnpm run lint

      - name: Build project
        run: pnpm run build

      - name: Run tests 🧪
        run: pnpm run test -- --coverage

      - name: Coverage
        uses: codecov/codecov-action@v5
